name: future_interceptor
description: "Integrate Interceptors into an asynchronous operation, inspired by Dio."
version: 0.1.0
homepage: https://github.com/XuanTung95/future_interceptor.git

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:

dev_dependencies:
  test:
